name: Build Padavan Firmware for JDC-1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
            cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
            pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget \
            libssl-dev openssl

      - name: Clone Padavan source
        run: |
          git clone --depth=1 https://github.com/advv123/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh

      - name: Modify firmware config
        run: |
          cd /opt/rt-n56u/trunk
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config
          echo "CONFIG_USB_USBNET=y" >> .config
          echo "CONFIG_USB_NET_RNDIS_HOST=y" >> .config
          echo "CONFIG_USB_NET_CDCETHER=y" >> .config
          echo "CONFIG_USB_NET_CDC_NCM=y" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=y/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n/g' .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=y/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/g' .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=y/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_SRELAY=y/CONFIG_FIRMWARE_INCLUDE_SRELAY=n/g' .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n/g' .config

      - name: Build firmware
        env:
          TNAME: JDC-1
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
          OPENSSL_LIBS: "-lssl -lcrypto"
          OPENSSL_CFLAGS: "-I/usr/include"
        run: |
          cd /opt/rt-n56u/trunk
          fakeroot ./build_firmware_modify $TNAME
          sudo ./clear_tree
          sudo ./build_firmware_modify $TNAME 0
          mkdir -p /opt/images
          sudo mv -f images/*.trx /opt/images/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: JDC-1-firmware
          path: /opt/images/*.trx
