name: Build Padavan Firmware for JDC-1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
            cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
            pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget \
            libssl-dev openssl

      - name: Clone Padavan source
        run: |
          git clone --depth=1 https://github.com/advv123/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh

      - name: Patch AdGuardHome download
        run: |
          cd /opt/rt-n56u/trunk/tools
          # 获取最新版本号
          AGH_VER=$(curl -s https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | grep tag_name | cut -d '"' -f4)
          AGH_URL="https://github.com/AdguardTeam/AdGuardHome/releases/download/${AGH_VER}/AdGuardHome_linux_mipsle.tar.gz"
          echo "Downloading AdGuardHome from $AGH_URL"
          wget -O AdGuardHome_linux_mipsle.tar.gz "$AGH_URL" || (echo "❌ 下载失败: $AGH_URL" && exit 1)

      - name: Modify firmware config
        run: |
          cd /opt/rt-n56u/trunk
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config
          echo "CONFIG_USB_USBNET=y" >> .config
          echo "CONFIG_USB_NET_RNDIS_HOST=y" >> .config
          echo "CONFIG_USB_NET_CDCETHER=y" >> .config
          echo "CONFIG_USB_NET_CDC_NCM=y" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config

      - name: Build firmware
        env:
          TNAME: JDC-1
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
          OPENSSL_LIBS: "-lssl -lcrypto"
          OPENSSL_CFLAGS: "-I/usr/include"
        run: |
          cd /opt/rt-n56u/trunk
          fakeroot ./build_firmware_modify $TNAME
          sudo ./clear_tree
          sudo ./build_firmware_modify $TNAME 0
          mkdir -p /opt/images
          sudo mv -f images/*.trx /opt/images/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: JDC-1-firmware
          path: /opt/images/*.trx
